    SPI_4wire_inst __(.clk_i( ),
        .rst_n_i( ),
        .sclk_i( ),
        .PSEL( ),
        .PENABLE( ),
        .PADDR( ),
        .PWRITE( ),
        .PWDATA( ),
        .PRDATA( ),
        .PREADY( ),
        .PSLVERR( ),
        .SCLK( ),
        .DC( ),
        .CS( ),
        .SDIN( ),
        .RST( ));
